#include "polarconfig.h"
#include <list>
#include <iostream>
namespace polarconfig{
 std::list<double> disp_allba_x;
 std::list<double> disp_allba_y;
 std::list<double> disp_allba_z;
 std::list<double> disp_allca_x;
 std::list<double> disp_allca_y;
 std::list<double> disp_allca_z;
 std::list<double> disp_ca_scalar;
 std::list<double> disp_ba_scalar;
 std::list<double> disp_B_scalar;
 std::list<double> disp_allB_x;
 std::list<double> disp_allB_y;
 std::list<double> disp_allB_z;
 std::list<double> tilt_angle;
 std::list<double> tilt_angle_one;
 std::list<double> tilt_angle_two;
 std::list<double> tilt_angle_three;
 std::list<double> la_x;
 std::list<double> la_y;
 std::list<double> la_z;
 std::list<double> px;
 std::list<double> py;
 std::list<double> pz;
}
